### PR TITLE
Added fastlane plugin

### PR DESCRIPTION
**Pull request by KrauseFx**
Related https://github.com/fastlane/fastlane/pull/4722

### CODE REVIEW

**Comment by KrauseFx** [comment]
The test failures don't seem related to my PR.

**Comment by jcampbell05** [comment]
@KrauseFx  Yeah thats unrelated I have a fix in a separate PR, thanks for this Felix 🚀 Excited to support Fastlane Plugins !

**Comment by KrauseFx** [comment]
Super excited to see this merged 🚀

**Comment by KrauseFx** [comment]
You might want to delete the fastlane action from your folder

**Comment by jcampbell05** [comment]
@krausefx the one bundled with fastlane you mean ? Super excited for plugins !

**Comment by KrauseFx** [comment]
You have the action in this repo in some subfolder already

**Pull request merged**
