### PR TITLE
Simplify configuration property implementation

### PR DESCRIPTION
**Pull request by therealbnut**
Basically this changes the DSL in this way:
```diff
- all_configurations.supported_devices = :iphone_only
+ all_configurations.each { |c| c.supported_devices = :iphone_only }
```

It's implemented by joining `debug` and `release`, instead of storing a separate `all_configurations` property.

Admittedly it's not as concise, but it has the following advantages:
 * works the same way as `release_configurations`, `debug_configurations`
 * removes the need for a `flatten_configurations` concept.
 * `defaults` are baked into configurations on first use, so now you can remove default values.
 * should fix https://github.com/jcampbell05/xcake/issues/43 (overwriting `all_configurations` values).

#### Preserving the DSL (Future Work and Alternative Approaches)

1. New fields could be added `:default_configuration`, `:default_release_configuration`, `:default_debug_configuration` which are merged (like `flatten_configurations` was) to produce the default `(debug|release)_configuration` values. These values can be modified prior to building new configurations to change them uniformly.
2. The DSL could be preserved with new classes with custom property accessors, but property values are undefined if each configuration has a different value. I wouldn't recommend this.

### CODE REVIEW

**Comment by therealbnut** [comment]
oh my, `houndci` surprise! I don't do Ruby much, I'll have to work out how to run that locally.

**Comment by jcampbell05** [comment]
@therealbnut this is amazing ❤️! Could you updated the documentation to reflect the new syntax and then I'll be happy to merge :)

**Comment by therealbnut** [comment]
No problem (it's 11:30pm, so I may have to do it tomorrow if it's a large task). Do you want me to push a squash commit?

**Comment by jcampbell05** [comment]
@therealbnut Yes that would be useful.

**Comment by therealbnut** [comment]
Which documentation did you mean? [Cakefile.md](docs/Cakefile.md) seems to be fairly good to me (except for a typo).

**Comment by jcampbell05** [comment]
Thanks for this @therealbnut  :) !  Great job :)

**Pull request merged**
