### PR TITLE
Test/Fix `xcconfig` integration

### PR DESCRIPTION
**Pull request by therealbnut**
It's still WIP, but this branch seems to address the issue (#66) for me:
https://github.com/jcampbell05/xcake/compare/therealbnut-adjust-xcconfig
It seems strange that it ever worked, so it would be good if you could verify if the old code works for you @jcampbell05. Also whether or not this fixes it for you :)

It's quite possible I've got some weirdness in my setup. I've done a lot of hacking around with xcodeproj in the past, it's possible I've somehow messed up my gems through my inexperience with ruby.

The issue seems to be two-fold, the `xcconfig` is added to the project, not the [configuration](http://www.rubydoc.info/github/CocoaPods/Xcodeproj/Xcodeproj/Project/Object/XCBuildConfiguration#base_configuration_reference-instance_method).
```diff
- native_configuration_object.base_configuration_reference = xcconfig
+ build_configuration.base_configuration_reference = xcconfig
```

The test verified the wrong thing (if I'm correct), so it wasn't picked up:
```diff
- expect(@native_configurable).to receive(:base_configuration_reference=).with(xcconfig)
+ expect(@native_configuration).to receive(:base_configuration_reference=).with(xcconfig)
```

---

You may also be interested on that branch, I've added this:
```diff
- project.instance_eval(file_contents)
+ project.instance_eval(file_contents, file_path)
```
It seems to print out nicer debugging info (the path of the Cakefile), when there's an error.

### CODE REVIEW

**Comment by therealbnut** [comment]
Hey, I'm trying to verify the change in coverage:
https://coveralls.io/builds/6084430/source?filename=spec%2Fproject%2Fsugar_spec.rb

It's giving me the following message:
> **SOURCE NOT AVAILABLE**
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

**Comment by jcampbell05** [comment]
@therealbnut  Thanks for the heads up I'll re authenticate :)

**Comment by jcampbell05** [comment]
I've tried fixing it can you give it a go :)

**Comment by therealbnut** [comment]
I've pushed a commit that should trigger the build bot again

**Comment by therealbnut** [comment]
Unfortunately I haven't got much time to fix this at the moment. To do it properly I think it would need something like this ([xcconfig_file_reference_installer.rb](https://github.com/jcampbell05/xcake/blob/025ed71d42d955ef1cf11a65b275d98a91cb5de0/lib/xcake/file_reference_installer/xcconfig_file_reference_installer.rb#L6)):

> `# TODO: In future we will implement a 2 phase file installer system.`

The xcconfig should use the file nodes to ensure they're added to the project properly, but that same node needs to be used by the configuration to add the xcconfig to the target.

**Comment by jcampbell05** [comment]
@therealbnut  thanks for your progress, I'll check it out and let you know my thoughts here so we can discuss it :)

**Comment by jcampbell05** [comment]
This is looking good @therealbnut. I just need to make the tests pass and I'll verify with a xcode project (I'm hoping to have integration tests in the future for xcode projects.

**Comment by therealbnut** [comment]
Great, let me know if you want me to review/verify your changes (I may not have time until the weekend though)

**Comment by jcampbell05** [comment]
@therealbnut  sorry about letting this die, I'll try to merge in master as I think it should be passing now.

**Comment by therealbnut** [comment]
Cool, thanks, you may want to verify functionality/regressions first - it has been a while and I can't remember why it was marked WIP.

**Comment by jcampbell05** [comment]
@therealbnut yeah needs a bit of work to fix ocnflicts and get tests passing :)

**Comment by jcampbell05** [comment]
Got it passing and working, will need some additional work when I start on `0.7` of Xcake as I'll be refactoring the file system to make these sorts of tasks easier :)

**Pull request merged**
