### PR TITLE
Fixes: the configuration wasn't named if you don't specify the name

### PR DESCRIPTION
**Pull request by colinta**

### CODE REVIEW

**Comment by colinta** [comment]
Noticed this after installing the latest build.

**Comment by colinta** [comment]
Ah, I think the name should be capitalized

```
		36693110CF66B9EBCCFE6C6B /* debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
...
```

**Comment by jcampbell05** [comment]
Yeah ideally it should be capitalised like the Xcode defaults so we don't break compatibility with existing scripts.
But great work!

**Comment by colinta** [comment]
:+1:

**Comment by jcampbell05** [comment]
Thanks for this @colinta, keep the PRS coming ! :) :rocket:

**Comment by colinta** [comment]
I might have another soon actually!  In a fresh project, I get this weird error when setting a configuration on a project.

```ruby
project do |p|
...
  p.debug_configuration.settings["ENABLE_TESTABILITY"] = "YES"
end
```

```
xcake make
...
Saving Scheme List...
2016-01-22 14:45:35.839 ruby[5343:1844025] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-9523/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/DataModel/Containers/PBXProject.m:2511
Details:  Configuration does not have a name: <XCBuildConfiguration:0x7f90af74aa20:A2A16E9345CA877BA78FD32B:name='':buildSettings(28)={ (mutable)
   ALWAYS_SEARCH_USER_PATHS = 【NO】
   CLANG_CXX_LANGUAGE_STANDARD = 【gnu++0x】
   CLANG_CXX_LIBRARY = 【libc++】
   CLANG_ENABLE_MODULES = 【YES】
   CLANG_ENABLE_OBJC_ARC = 【YES】
   CLANG_WARN_BOOL_CONVERSION = 【YES】
   CLANG_WARN_CONSTANT_CONVERSION = 【YES】
   CLANG_WARN_DIRECT_OBJC_ISA_USAGE = 【YES】
   CLANG_WARN_EMPTY_BODY = 【YES】
   CLANG_WARN_ENUM_CONVERSION = 【YES】
   CLANG_WARN_INT_CONVERSION = 【YES】
   CLANG_WARN_OBJC_ROOT_CLASS = 【YES】
   CLANG_WARN_UNREACHABLE_CODE = 【YES】
   CLANG_WARN__DUPLICATE_METHOD_MATCH = 【YES】
   COPY_PHASE_STRIP = 【NO】
   ENABLE_TESTABILITY = 【YES】
   GCC_C_LANGUAGE_STANDARD = 【gnu99】
   GCC_DYNAMIC_NO_PIC = 【NO】
   GCC_OPTIMIZATION_LEVEL = 【0】
   GCC_PREPROCESSOR_DEFINITIONS = 【𝗡𝗼𝗻𝗹𝗶𝘁𝗲𝗿𝗮𝗹𝗔𝗿𝗿𝗮𝘆:【DEBUG=1】,【𝗦𝘂𝗯𝘀𝘁𝗶𝘁𝘂𝘁𝗶𝗼𝗻:【inherited】】】
   GCC_SYMBOLS_PRIVATE_EXTERN = 【NO】
   GCC_WARN_64_TO_32_BIT_CONVERSION = 【YES】
   GCC_WARN_ABOUT_RETURN_TYPE = 【YES】
   GCC_WARN_UNDECLARED_SELECTOR = 【YES】
   GCC_WARN_UNINITIALIZED_AUTOS = 【YES】
   GCC_WARN_UNUSED_FUNCTION = 【YES】
   GCC_WARN_UNUSED_VARIABLE = 【YES】
   ONLY_ACTIVE_ARCH = 【YES】
}>
Object:   <PBXProject: 0x7f90b0c43620>
Method:   -cachedMacroExpansionScopeForWorkspaceArenaSnapshot:configurationNamed:
Thread:   <NSThread: 0x7f90abdd6480>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x00000001039fec2d -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x00000001039fe761 _DVTAssertionHandler (in DVTFoundation)
  2  0x00000001039fe978 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000109e5dac7 -[PBXProject cachedMacroExpansionScopeForWorkspaceArenaSnapshot:configurationNamed:] (in DevToolsCore)
  4  0x0000000109e5df09 -[PBXProject cachedMacroExpansionScopeForBuildParameters:] (in DevToolsCore)
  5  0x0000000109e5e0a2 -[PBXProject expandedValueForString:forBuildParameters:] (in DevToolsCore)
  6  0x0000000109e734e8 -[PBXReference expandedValueForString:forBuildParameters:] (in DevToolsCore)
  7  0x0000000109e740e1 -[PBXReference _evaluatedPathForSourceTree:appendPathWhenExpanded:forBuildParameters:] (in DevToolsCore)
  8  0x0000000109e7474c -[PBXReference absolutePathForBuildParameters:] (in DevToolsCore)
  9  0x0000000109e74907 -[PBXReference absolutePath] (in DevToolsCore)
 10  0x0000000109e79ecf -[PBXFileReference _getEffectiveFileType:fileProperties:] (in DevToolsCore)
 11  0x0000000109e7a0cc -[PBXFileReference fileType] (in DevToolsCore)
 12  0x0000000109e7c5f5 -[PBXFileReference awakeFromPListUnarchiver:] (in DevToolsCore)
 13  0x00007fff8b14cad6 -[NSArray makeObjectsPerformSelector:withObject:] (in CoreFoundation)
 14  0x0000000109e8936e -[PBXPListUnarchiver decodeRootObject] (in DevToolsCore)
 15  0x0000000109e5331d +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
 16  0x0000000109e541b6 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
 17  0x00007fff973dbf14 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6
```

Changing that line to ```p.debug_configuration(:Debug).settings["ENABLE_TESTABILITY"] =     "YES"``` resolves it.

**Comment by colinta** [comment]
OH!  Duh, I'm using the gem version!  haha, this PR fixes this issue.

**Comment by jcampbell05** [comment]
haha :) I'll push up a new version fairly soon. But I guess use `master` until then ?

**Pull request merged**
