### PR TITLE
first pass at Shell Script build phases

### PR DESCRIPTION
**Pull request by colinta**
This code generates a shell script build phase from a Cakefile:

```ruby
    target.shell_script_build_phase("Generate warnings for focused tests", <<-SCRIPT)
        KEYWORDS="fdescribe|fcontext|fit"
        FILE_EXTENSIONS="swift"
        find -E "${SRCROOT}/Specs/" -regex ".*\\.($FILE_EXTENSIONS)$" -print0 | xargs -0 egrep --with-filename --line-number --only-matching "($KEYWORDS)\\(.*\\$" | perl -p -e "s/(?:$KEYWORDS)\\(\\"(.*)\\".*/ warning: Focused Spec: \\$1/"
    SCRIPT
```

### CODE REVIEW

**Comment by colinta** [comment]
I have to go home now, and I think there's lots of room for improvement here (for one, `ShellScriptBuildPhase` should have a parent class, I think).

**Comment by jcampbell05** [comment]
Cheers for this @colinta :) I'll have a think about this as I'm doing some work in this area for the Apple Watch.

**Comment by colinta** [comment]
(rebased to clean up the commits)

**Comment by jcampbell05** [comment]
I think this looks good @colinta if we can get the tests passing then we can merge it in.

You may be right about the super class but I think we can get it in and evolve it into something more complete (No point over engineering at this point). We potentially may tweak the design in the future, as I'm going to have to make some changes to the way Xcake creates the build phases. I'll raise an issue about this so we can keep track of all the parts :).

**Comment by colinta** [comment]
Cool! I agree. Can do.

**Comment by jcampbell05** [comment]
Cool, thanks :)

**Comment by colinta** [comment]
Oops, this included some code I was using locally.  I was having trouble using `exclude_files`, and so I rewrote it to exclude the files *before* traversing the file tree, instead of calling `remove_children_with_path`.

```
        if target.include_files
          files = Dir.glob(target.include_files)
          if target.exclude_files
            excluded = Dir.glob(target.exclude_files)
            files.select! do |file|
              !excluded.include?(file)
            end
          end

          files.each do |file|
            @root_node.create_children_with_path(file, @native_target)
          end
        end
```

**Comment by colinta** [comment]
(I didn't include this :point_up: code in this PR)

**Comment by jcampbell05** [comment]
@colinta  Ohh what was the trouble ?

**Comment by colinta** [comment]
I'll have to investigate it again on Wednesday, but did you see this error? <https://travis-ci.org/jcampbell05/xcake/jobs/104949320>

Specs are passing in the other Ruby versions.

**Comment by colinta** [comment]
It must have been a red herring, because stashing that change and running it now is working fine.  I was having trouble excluding a playground folder (```target.exclude_files = ["**/*.playground", "**/*.playground/**/*"]```).

**Comment by colinta** [comment]
(I keep saying "I'll look at it on Wednesday", and then looking at it! :wink:)

**Comment by jcampbell05** [comment]
Ah must have been, still pretty wild :) but I'm glad. Ah good catch, I should add support for including playgrounds in a separate PR for projects who use them :).

(haha glad you're enjoying it! :) Really appreciate your help!)

**Comment by jcampbell05** [comment]
Thanks for the contribution 🚀:)

**Pull request merged**
