### PR TITLE
Copy files build phases

### PR DESCRIPTION
**Pull request by earien**
Fixed the crash and Cakefile documentation reported in #158 .
Added destination options and spec tests.

### CODE REVIEW

**Comment by jcampbell05** [comment]
This is looking great 👍 if you could get the tests passing :)

**Comment by earien** [comment]
hey there @jcampbell05 :D are u referring to the travis build? 🤔 it seems to be failing due to the change in the gemspec file in this [commit](https://github.com/jcampbell05/xcake/commit/361bd6578766cbef923567c9fd95902e6574b8c8) : travis is trying to build for xcodeproj 1.3, but it is invalid as xcodeproj >=1.4.0 is now required.

**Comment by jcampbell05** [comment]
@earien Ah I see :) I wonder if I need to change the machine we are running on

**Comment by earien** [comment]
Are you using some `xcodeproj` API not available in 1.3.0? in this case, as you changed the minimum requirements for `xcodeproj`to be 1.4.0 in the Gemspec file, the travis jobs that check the compatibility with xcodeproj 1.3.0 are not needed anymore. Otherwise, just revert the minimum version of xcodeproj to be 1.3.0, and it should work again 😄

**Comment by jcampbell05** [comment]
@earien Ideally I shouldnt be but Ill take a look :)

**Pull request merged**
