### PR TITLE
Minor fixes in documentation

### PR DESCRIPTION
**Pull request by maximkhatskevich**
Fixes:
- https://github.com/jcampbell05/xcake/issues/61
- https://github.com/jcampbell05/xcake/issues/60

### CODE REVIEW

**Comment by jcampbell05** [comment]
@maximkhatskevich  Many thanks :) would you like to join our team of contributors ?

**Comment by maximkhatskevich** [comment]
@jcampbell05 sure, I don't mind, but I'm not a Ruby developer, I do not know Ruby so won't be able to help with development (I'm iOS developer), but will do my best to help with documentation and testing, as I've engaged this library into my project on my full time job.

**Comment by jcampbell05** [comment]
@maximkhatskevich sure, that will be a big help! and thank you for choosing to use xcake!

**Comment by maximkhatskevich** [comment]
Okay, thanks :) And thank you for creating that tool, I just started using it, but it should be really huge improvement on merging different branches!

**Pull request merged**
